name: Call_API

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
    
  schedule:
    - cron: '0 1,5,8 * * 1-5'
    
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Deploy the Python environment
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        
    - name: Installing requests
      run: |
        pip install requests
        
    - name: Read config from secrets
      env: 
        ID_LIST: ${{ secrets.ID_LIST }} # secrets_id 提供
        KEY_LIST: ${{ secrets.KEY_LIST }} # secrets_key 提供
        ID_LIST2: ${{ secrets.ID_LIST2 }} # secrets_id 提供
        KEY_LIST2: ${{ secrets.KEY_LIST2 }} # secrets_key 提供
      run: | 
        echo $ID_LIST > idlist.txt
        echo $KEY_LIST > keylist.txt
        sed -i '10 r idlist.txt' call.py
        sed -i '11 r keylist.txt' call.py
        echo $ID_LIST2 > idlist2.txt
        echo $KEY_LIST2 > keylist2.txt
        sed -i '12 r idlist2.txt' call.py
        sed -i '13 r keylist2.txt' call.py
        
    - name: Call the API
      run: | 
        python call.py
